on:
  push:
    branches:
      - master
      - charlie-dev
jobs:
  build:
    runs-on: self-hosted-docker
    steps:
      - uses: actions/checkout@v3
      - name: does powershell work?
        run: |
          apt update -y
          apt install -y powershell
          pwsh -File ./test.ps1
          