name: "Run TODO to Issue"
on:
    push:
        branches:
        - main
        - charlie-dev
jobs:
  build:
    runs-on: self-hosted-docker
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: https://github.com/alstr/todo-to-issue-action@master
        with:
          INSERT_ISSUE_URLS: "true"
      - name: Set Git user
        run: |
          git config --global user.name "gayhub-actions[bot :3]"
          git config --global user.email "charliesan@envs.net"
      - name: Commit and Push Changes
        run: |
          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "Automatically added GitHub issue links to TODOs"
            git push origin main
          else
            echo "No changes to commit"
          fi