name: Create issues from todos

on:
  push:
    branches:
      - master
      - charlie-dev

jobs:
  todos:
    runs-on: self-hosted-docker
    steps:
        - uses: actions/checkout@v1
        - name: todo-actions
          uses: https://github.com/dtinth/todo-actions
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}