on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted-docker
    steps:
      - uses: actions/checkout@v3
      - uses: https://github.com/actions/setup-java@main
        with:
          distribution: 'oracle' # not too sure if this works
          java-version: '21'
      - name: Build JMASM
        run: |
          apt update -y
          apt install -y build-essential openjdk22-jdk maven
          mvn clean install package

          mv $(find . -name "*-jar-with-dependencies.jar") jmasm.jar

          tar -cJf jmasm-build.tar.zst jmasm.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jmasm-build
          path: jmasm-build.tar.zst