on:
  push:
    branches:
      - master
      - charlie-dev

jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v3
      - uses: https://github.com/actions/setup-java@main
        with:
          distribution: 'oracle' # not too sure if this works
          java-version: '22'
      - name: Build JMASM and test it
        run: |
          apt update -y
          apt install -y build-essential maven
      - name: test the bastards
        run: |
          mvn test
